# EssentialsX Pocketmine-MP port configuration!
# Made by Wockgod
# Discord: `woccck`
# (!) DO NOT CHANGE (!)
version: 1.0.1

# The character(s) to prefix all nicknames, so that you know they are not true usernames.
# Users with essentialsx.nick.hideprefix will not be prefixed with the character(s)
nickname-prefix: '~'

# The maximum length allowed in nicknames. The nickname prefix is not included in this.
max-nick-length: 15

# A list of phrases that cannot be used in nicknames. You can include regular expressions here.
# Users with essentialsx.nick.blacklist.bypass will be able to bypass this filter.
nick-blacklist:
#- Notch
#- '^Dinnerbone'

# When this option is enabled, nickname length checking will exclude color codes in player names.
# ie: "&6Notch" has 7 characters (2 are part of a color code), a length of 5 is used when this option is set to true
ignore-colors-in-max-nick-length: false

# Cooldowns for commands in seconds
command-cooldowns:
  feed: 10 # 10 Seconds
  home: 70 # 1 minute 10 seconds
  heal: 60 # 1 minute

# Vanilla Enchantments
# Ores that fortune activates on
fortune.blocks:
  - coal_ore
  - iron_ore
  - gold_ore
  - diamond_ore
  - leaves
  - nether_quartz_ore
  - glowstone
  - redstone_ore
  - emerald_ore
  - glowing_redstone_ore

# Entities that looting will work on.
looting.entities:
  drop_multiplier: 2
  zombie:
    - "rotten_flesh" # Rotten Flesh drop
  skeleton:
    - "bone" # Bone drop
    - "arrow" # Arrow drop
  creeper:
    - "gunpowder" # Gunpowder drop
  spider:
    - "string" # String drop
    - "spider_eye" # Spider Eye drop
  enderman:
    - "ender_pearl" # Ender Pearl drop
  chicken:
    - "feather" # Feather drop
    - "raw_chicken" # Raw Chicken drop
  cow:
    - "leather" # Leather drop
    - "beef" # Beef drop
  pig:
    - "porkchop" # Porkchop drop
  sheep:
    - "wool" # Wool dro
  blaze:
    - "blaze_rod" # Blaze Rod drop

# Near Radius
# The default radius with /near
near-radius: 200
