# EssentialsX Pocketmine-MP port configuration!
# Made by Wockgod
# Discord: `woccck`
# (!) DO NOT CHANGE (!)
version: 1.0.0

# Vanilla Enchantments
# Ores that fortune activates on
fortune.blocks:
  - coal_ore
  - iron_ore
  - gold_ore
  - diamond_ore
  - leaves
  - nether_quartz_ore
  - glowstone
  - redstone_ore
  - emerald_ore
  - glowing_redstone_ore

# Entities that looting will work on.
looting.entities:
  drop_multiplier: 2
  zombie:
    - "rotten_flesh" # Rotten Flesh drop
  skeleton:
    - "bone" # Bone drop
    - "arrow" # Arrow drop
  creeper:
    - "gunpowder" # Gunpowder drop
  spider:
    - "string" # String drop
    - "spider_eye" # Spider Eye drop
  enderman:
    - "ender_pearl" # Ender Pearl drop
  chicken:
    - "feather" # Feather drop
    - "raw_chicken" # Raw Chicken drop
  cow:
    - "leather" # Leather drop
    - "beef" # Beef drop
  pig:
    - "porkchop" # Porkchop drop
  sheep:
    - "wool" # Wool dro
  blaze:
    - "blaze_rod" # Blaze Rod drop

# Near Radius
# The default radius with /near
near-radius: 200
